# Generated by Django 4.2.3 on 2023-08-01 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Brand",
            },
        ),
        migrations.CreateModel(
            name="Engine",
            fields=[
                (
                    "engine_number",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("specs", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Engine",
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Feature",
            },
        ),
        migrations.CreateModel(
            name="ShowRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("picture", models.ImageField(blank=True, null=True, upload_to="")),
                ("position", models.CharField(max_length=100)),
                (
                    "showroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showroomapp.showroom",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staff",
            },
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showroomapp.brand",
                    ),
                ),
                (
                    "engine",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showroomapp.engine",
                    ),
                ),
                ("features", models.ManyToManyField(to="showroomapp.feature")),
            ],
            options={
                "verbose_name_plural": "Model",
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "chassis_number",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showroomapp.model",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Car",
            },
        ),
    ]
